// -------------------------------------------------------------
//
// Module: filter
// Generated by MATLAB(R) 9.7 and Filter Design HDL Coder 3.1.6.
// Generated on: 2020-09-11 17:08:13
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// TargetDirectory: C:\Users\86150\Desktop\verilog\fir30k
// TargetLanguage: Verilog
// TestBenchStimulus: impulse step ramp chirp noise 
// GenerateHDLTestBench: off

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 31
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,18 -> [-1.250000e-01 1.250000e-01)
// Input             : s9,8 -> [-1 1)
// Filter Internals  : Specify Precision
//   Output          : s9,8 -> [-1 1)
//   Product         : s31,31 -> [-5.000000e-01 5.000000e-01)
//   Accumulator     : s34,31 -> [-4 4)
//   Round Mode      : convergent
//   Overflow Mode   : wrap
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module filter
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [8:0] filter_in; //sfix9_En8
  output  signed [8:0] filter_out; //sfix9_En8

////////////////////////////////////////////////////////////////
//Module Architecture: filter
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b1001101000000110; //sfix16_En18
  parameter signed [15:0] coeff2 = 16'b1100000010110010; //sfix16_En18
  parameter signed [15:0] coeff3 = 16'b0101100011101010; //sfix16_En18
  parameter signed [15:0] coeff4 = 16'b1100011100011111; //sfix16_En18
  parameter signed [15:0] coeff5 = 16'b1111000001001110; //sfix16_En18
  parameter signed [15:0] coeff6 = 16'b0010110010010001; //sfix16_En18
  parameter signed [15:0] coeff7 = 16'b0000011100110111; //sfix16_En18
  parameter signed [15:0] coeff8 = 16'b1011101011101010; //sfix16_En18
  parameter signed [15:0] coeff9 = 16'b0011001011110011; //sfix16_En18
  parameter signed [15:0] coeff10 = 16'b0001111110100011; //sfix16_En18
  parameter signed [15:0] coeff11 = 16'b1011100010010010; //sfix16_En18
  parameter signed [15:0] coeff12 = 16'b0000110011010100; //sfix16_En18
  parameter signed [15:0] coeff13 = 16'b0100010000110010; //sfix16_En18
  parameter signed [15:0] coeff14 = 16'b1100001001010111; //sfix16_En18
  parameter signed [15:0] coeff15 = 16'b1110010111010101; //sfix16_En18
  parameter signed [15:0] coeff16 = 16'b0100111011111110; //sfix16_En18
  parameter signed [15:0] coeff17 = 16'b1110010111010101; //sfix16_En18
  parameter signed [15:0] coeff18 = 16'b1100001001010111; //sfix16_En18
  parameter signed [15:0] coeff19 = 16'b0100010000110010; //sfix16_En18
  parameter signed [15:0] coeff20 = 16'b0000110011010100; //sfix16_En18
  parameter signed [15:0] coeff21 = 16'b1011100010010010; //sfix16_En18
  parameter signed [15:0] coeff22 = 16'b0001111110100011; //sfix16_En18
  parameter signed [15:0] coeff23 = 16'b0011001011110011; //sfix16_En18
  parameter signed [15:0] coeff24 = 16'b1011101011101010; //sfix16_En18
  parameter signed [15:0] coeff25 = 16'b0000011100110111; //sfix16_En18
  parameter signed [15:0] coeff26 = 16'b0010110010010001; //sfix16_En18
  parameter signed [15:0] coeff27 = 16'b1111000001001110; //sfix16_En18
  parameter signed [15:0] coeff28 = 16'b1100011100011111; //sfix16_En18
  parameter signed [15:0] coeff29 = 16'b0101100011101010; //sfix16_En18
  parameter signed [15:0] coeff30 = 16'b1100000010110010; //sfix16_En18
  parameter signed [15:0] coeff31 = 16'b1001101000000110; //sfix16_En18

  // Signals
  reg  signed [8:0] delay_pipeline [0:30] ; // sfix9_En8
  wire signed [30:0] product31; // sfix31_En31
  wire signed [24:0] mul_temp; // sfix25_En26
  wire signed [30:0] product30; // sfix31_En31
  wire signed [24:0] mul_temp_1; // sfix25_En26
  wire signed [30:0] product29; // sfix31_En31
  wire signed [24:0] mul_temp_2; // sfix25_En26
  wire signed [30:0] product28; // sfix31_En31
  wire signed [24:0] mul_temp_3; // sfix25_En26
  wire signed [30:0] product27; // sfix31_En31
  wire signed [24:0] mul_temp_4; // sfix25_En26
  wire signed [30:0] product26; // sfix31_En31
  wire signed [24:0] mul_temp_5; // sfix25_En26
  wire signed [30:0] product25; // sfix31_En31
  wire signed [24:0] mul_temp_6; // sfix25_En26
  wire signed [30:0] product24; // sfix31_En31
  wire signed [24:0] mul_temp_7; // sfix25_En26
  wire signed [30:0] product23; // sfix31_En31
  wire signed [24:0] mul_temp_8; // sfix25_En26
  wire signed [30:0] product22; // sfix31_En31
  wire signed [24:0] mul_temp_9; // sfix25_En26
  wire signed [30:0] product21; // sfix31_En31
  wire signed [24:0] mul_temp_10; // sfix25_En26
  wire signed [30:0] product20; // sfix31_En31
  wire signed [24:0] mul_temp_11; // sfix25_En26
  wire signed [30:0] product19; // sfix31_En31
  wire signed [24:0] mul_temp_12; // sfix25_En26
  wire signed [30:0] product18; // sfix31_En31
  wire signed [24:0] mul_temp_13; // sfix25_En26
  wire signed [30:0] product17; // sfix31_En31
  wire signed [24:0] mul_temp_14; // sfix25_En26
  wire signed [30:0] product16; // sfix31_En31
  wire signed [24:0] mul_temp_15; // sfix25_En26
  wire signed [30:0] product15; // sfix31_En31
  wire signed [24:0] mul_temp_16; // sfix25_En26
  wire signed [30:0] product14; // sfix31_En31
  wire signed [24:0] mul_temp_17; // sfix25_En26
  wire signed [30:0] product13; // sfix31_En31
  wire signed [24:0] mul_temp_18; // sfix25_En26
  wire signed [30:0] product12; // sfix31_En31
  wire signed [24:0] mul_temp_19; // sfix25_En26
  wire signed [30:0] product11; // sfix31_En31
  wire signed [24:0] mul_temp_20; // sfix25_En26
  wire signed [30:0] product10; // sfix31_En31
  wire signed [24:0] mul_temp_21; // sfix25_En26
  wire signed [30:0] product9; // sfix31_En31
  wire signed [24:0] mul_temp_22; // sfix25_En26
  wire signed [30:0] product8; // sfix31_En31
  wire signed [24:0] mul_temp_23; // sfix25_En26
  wire signed [30:0] product7; // sfix31_En31
  wire signed [24:0] mul_temp_24; // sfix25_En26
  wire signed [30:0] product6; // sfix31_En31
  wire signed [24:0] mul_temp_25; // sfix25_En26
  wire signed [30:0] product5; // sfix31_En31
  wire signed [24:0] mul_temp_26; // sfix25_En26
  wire signed [30:0] product4; // sfix31_En31
  wire signed [24:0] mul_temp_27; // sfix25_En26
  wire signed [30:0] product3; // sfix31_En31
  wire signed [24:0] mul_temp_28; // sfix25_En26
  wire signed [30:0] product2; // sfix31_En31
  wire signed [24:0] mul_temp_29; // sfix25_En26
  wire signed [33:0] product1_cast; // sfix34_En31
  wire signed [30:0] product1; // sfix31_En31
  wire signed [24:0] mul_temp_30; // sfix25_En26
  wire signed [33:0] sum1; // sfix34_En31
  wire signed [33:0] add_signext; // sfix34_En31
  wire signed [33:0] add_signext_1; // sfix34_En31
  wire signed [34:0] add_temp; // sfix35_En31
  wire signed [33:0] sum2; // sfix34_En31
  wire signed [33:0] add_signext_2; // sfix34_En31
  wire signed [33:0] add_signext_3; // sfix34_En31
  wire signed [34:0] add_temp_1; // sfix35_En31
  wire signed [33:0] sum3; // sfix34_En31
  wire signed [33:0] add_signext_4; // sfix34_En31
  wire signed [33:0] add_signext_5; // sfix34_En31
  wire signed [34:0] add_temp_2; // sfix35_En31
  wire signed [33:0] sum4; // sfix34_En31
  wire signed [33:0] add_signext_6; // sfix34_En31
  wire signed [33:0] add_signext_7; // sfix34_En31
  wire signed [34:0] add_temp_3; // sfix35_En31
  wire signed [33:0] sum5; // sfix34_En31
  wire signed [33:0] add_signext_8; // sfix34_En31
  wire signed [33:0] add_signext_9; // sfix34_En31
  wire signed [34:0] add_temp_4; // sfix35_En31
  wire signed [33:0] sum6; // sfix34_En31
  wire signed [33:0] add_signext_10; // sfix34_En31
  wire signed [33:0] add_signext_11; // sfix34_En31
  wire signed [34:0] add_temp_5; // sfix35_En31
  wire signed [33:0] sum7; // sfix34_En31
  wire signed [33:0] add_signext_12; // sfix34_En31
  wire signed [33:0] add_signext_13; // sfix34_En31
  wire signed [34:0] add_temp_6; // sfix35_En31
  wire signed [33:0] sum8; // sfix34_En31
  wire signed [33:0] add_signext_14; // sfix34_En31
  wire signed [33:0] add_signext_15; // sfix34_En31
  wire signed [34:0] add_temp_7; // sfix35_En31
  wire signed [33:0] sum9; // sfix34_En31
  wire signed [33:0] add_signext_16; // sfix34_En31
  wire signed [33:0] add_signext_17; // sfix34_En31
  wire signed [34:0] add_temp_8; // sfix35_En31
  wire signed [33:0] sum10; // sfix34_En31
  wire signed [33:0] add_signext_18; // sfix34_En31
  wire signed [33:0] add_signext_19; // sfix34_En31
  wire signed [34:0] add_temp_9; // sfix35_En31
  wire signed [33:0] sum11; // sfix34_En31
  wire signed [33:0] add_signext_20; // sfix34_En31
  wire signed [33:0] add_signext_21; // sfix34_En31
  wire signed [34:0] add_temp_10; // sfix35_En31
  wire signed [33:0] sum12; // sfix34_En31
  wire signed [33:0] add_signext_22; // sfix34_En31
  wire signed [33:0] add_signext_23; // sfix34_En31
  wire signed [34:0] add_temp_11; // sfix35_En31
  wire signed [33:0] sum13; // sfix34_En31
  wire signed [33:0] add_signext_24; // sfix34_En31
  wire signed [33:0] add_signext_25; // sfix34_En31
  wire signed [34:0] add_temp_12; // sfix35_En31
  wire signed [33:0] sum14; // sfix34_En31
  wire signed [33:0] add_signext_26; // sfix34_En31
  wire signed [33:0] add_signext_27; // sfix34_En31
  wire signed [34:0] add_temp_13; // sfix35_En31
  wire signed [33:0] sum15; // sfix34_En31
  wire signed [33:0] add_signext_28; // sfix34_En31
  wire signed [33:0] add_signext_29; // sfix34_En31
  wire signed [34:0] add_temp_14; // sfix35_En31
  wire signed [33:0] sum16; // sfix34_En31
  wire signed [33:0] add_signext_30; // sfix34_En31
  wire signed [33:0] add_signext_31; // sfix34_En31
  wire signed [34:0] add_temp_15; // sfix35_En31
  wire signed [33:0] sum17; // sfix34_En31
  wire signed [33:0] add_signext_32; // sfix34_En31
  wire signed [33:0] add_signext_33; // sfix34_En31
  wire signed [34:0] add_temp_16; // sfix35_En31
  wire signed [33:0] sum18; // sfix34_En31
  wire signed [33:0] add_signext_34; // sfix34_En31
  wire signed [33:0] add_signext_35; // sfix34_En31
  wire signed [34:0] add_temp_17; // sfix35_En31
  wire signed [33:0] sum19; // sfix34_En31
  wire signed [33:0] add_signext_36; // sfix34_En31
  wire signed [33:0] add_signext_37; // sfix34_En31
  wire signed [34:0] add_temp_18; // sfix35_En31
  wire signed [33:0] sum20; // sfix34_En31
  wire signed [33:0] add_signext_38; // sfix34_En31
  wire signed [33:0] add_signext_39; // sfix34_En31
  wire signed [34:0] add_temp_19; // sfix35_En31
  wire signed [33:0] sum21; // sfix34_En31
  wire signed [33:0] add_signext_40; // sfix34_En31
  wire signed [33:0] add_signext_41; // sfix34_En31
  wire signed [34:0] add_temp_20; // sfix35_En31
  wire signed [33:0] sum22; // sfix34_En31
  wire signed [33:0] add_signext_42; // sfix34_En31
  wire signed [33:0] add_signext_43; // sfix34_En31
  wire signed [34:0] add_temp_21; // sfix35_En31
  wire signed [33:0] sum23; // sfix34_En31
  wire signed [33:0] add_signext_44; // sfix34_En31
  wire signed [33:0] add_signext_45; // sfix34_En31
  wire signed [34:0] add_temp_22; // sfix35_En31
  wire signed [33:0] sum24; // sfix34_En31
  wire signed [33:0] add_signext_46; // sfix34_En31
  wire signed [33:0] add_signext_47; // sfix34_En31
  wire signed [34:0] add_temp_23; // sfix35_En31
  wire signed [33:0] sum25; // sfix34_En31
  wire signed [33:0] add_signext_48; // sfix34_En31
  wire signed [33:0] add_signext_49; // sfix34_En31
  wire signed [34:0] add_temp_24; // sfix35_En31
  wire signed [33:0] sum26; // sfix34_En31
  wire signed [33:0] add_signext_50; // sfix34_En31
  wire signed [33:0] add_signext_51; // sfix34_En31
  wire signed [34:0] add_temp_25; // sfix35_En31
  wire signed [33:0] sum27; // sfix34_En31
  wire signed [33:0] add_signext_52; // sfix34_En31
  wire signed [33:0] add_signext_53; // sfix34_En31
  wire signed [34:0] add_temp_26; // sfix35_En31
  wire signed [33:0] sum28; // sfix34_En31
  wire signed [33:0] add_signext_54; // sfix34_En31
  wire signed [33:0] add_signext_55; // sfix34_En31
  wire signed [34:0] add_temp_27; // sfix35_En31
  wire signed [33:0] sum29; // sfix34_En31
  wire signed [33:0] add_signext_56; // sfix34_En31
  wire signed [33:0] add_signext_57; // sfix34_En31
  wire signed [34:0] add_temp_28; // sfix35_En31
  wire signed [33:0] sum30; // sfix34_En31
  wire signed [33:0] add_signext_58; // sfix34_En31
  wire signed [33:0] add_signext_59; // sfix34_En31
  wire signed [34:0] add_temp_29; // sfix35_En31
  wire signed [8:0] output_typeconvert; // sfix9_En8
  reg  signed [8:0] output_register; // sfix9_En8

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[30] * coeff31;
  assign product31 = $signed({mul_temp[24:0], 5'b00000});

  assign mul_temp_1 = delay_pipeline[29] * coeff30;
  assign product30 = $signed({mul_temp_1[24:0], 5'b00000});

  assign mul_temp_2 = delay_pipeline[28] * coeff29;
  assign product29 = $signed({mul_temp_2[24:0], 5'b00000});

  assign mul_temp_3 = delay_pipeline[27] * coeff28;
  assign product28 = $signed({mul_temp_3[24:0], 5'b00000});

  assign mul_temp_4 = delay_pipeline[26] * coeff27;
  assign product27 = $signed({mul_temp_4[24:0], 5'b00000});

  assign mul_temp_5 = delay_pipeline[25] * coeff26;
  assign product26 = $signed({mul_temp_5[24:0], 5'b00000});

  assign mul_temp_6 = delay_pipeline[24] * coeff25;
  assign product25 = $signed({mul_temp_6[24:0], 5'b00000});

  assign mul_temp_7 = delay_pipeline[23] * coeff24;
  assign product24 = $signed({mul_temp_7[24:0], 5'b00000});

  assign mul_temp_8 = delay_pipeline[22] * coeff23;
  assign product23 = $signed({mul_temp_8[24:0], 5'b00000});

  assign mul_temp_9 = delay_pipeline[21] * coeff22;
  assign product22 = $signed({mul_temp_9[24:0], 5'b00000});

  assign mul_temp_10 = delay_pipeline[20] * coeff21;
  assign product21 = $signed({mul_temp_10[24:0], 5'b00000});

  assign mul_temp_11 = delay_pipeline[19] * coeff20;
  assign product20 = $signed({mul_temp_11[24:0], 5'b00000});

  assign mul_temp_12 = delay_pipeline[18] * coeff19;
  assign product19 = $signed({mul_temp_12[24:0], 5'b00000});

  assign mul_temp_13 = delay_pipeline[17] * coeff18;
  assign product18 = $signed({mul_temp_13[24:0], 5'b00000});

  assign mul_temp_14 = delay_pipeline[16] * coeff17;
  assign product17 = $signed({mul_temp_14[24:0], 5'b00000});

  assign mul_temp_15 = delay_pipeline[15] * coeff16;
  assign product16 = $signed({mul_temp_15[24:0], 5'b00000});

  assign mul_temp_16 = delay_pipeline[14] * coeff15;
  assign product15 = $signed({mul_temp_16[24:0], 5'b00000});

  assign mul_temp_17 = delay_pipeline[13] * coeff14;
  assign product14 = $signed({mul_temp_17[24:0], 5'b00000});

  assign mul_temp_18 = delay_pipeline[12] * coeff13;
  assign product13 = $signed({mul_temp_18[24:0], 5'b00000});

  assign mul_temp_19 = delay_pipeline[11] * coeff12;
  assign product12 = $signed({mul_temp_19[24:0], 5'b00000});

  assign mul_temp_20 = delay_pipeline[10] * coeff11;
  assign product11 = $signed({mul_temp_20[24:0], 5'b00000});

  assign mul_temp_21 = delay_pipeline[9] * coeff10;
  assign product10 = $signed({mul_temp_21[24:0], 5'b00000});

  assign mul_temp_22 = delay_pipeline[8] * coeff9;
  assign product9 = $signed({mul_temp_22[24:0], 5'b00000});

  assign mul_temp_23 = delay_pipeline[7] * coeff8;
  assign product8 = $signed({mul_temp_23[24:0], 5'b00000});

  assign mul_temp_24 = delay_pipeline[6] * coeff7;
  assign product7 = $signed({mul_temp_24[24:0], 5'b00000});

  assign mul_temp_25 = delay_pipeline[5] * coeff6;
  assign product6 = $signed({mul_temp_25[24:0], 5'b00000});

  assign mul_temp_26 = delay_pipeline[4] * coeff5;
  assign product5 = $signed({mul_temp_26[24:0], 5'b00000});

  assign mul_temp_27 = delay_pipeline[3] * coeff4;
  assign product4 = $signed({mul_temp_27[24:0], 5'b00000});

  assign mul_temp_28 = delay_pipeline[2] * coeff3;
  assign product3 = $signed({mul_temp_28[24:0], 5'b00000});

  assign mul_temp_29 = delay_pipeline[1] * coeff2;
  assign product2 = $signed({mul_temp_29[24:0], 5'b00000});

  assign product1_cast = $signed({{3{product1[30]}}, product1});

  assign mul_temp_30 = delay_pipeline[0] * coeff1;
  assign product1 = $signed({mul_temp_30[24:0], 5'b00000});

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{3{product2[30]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[33:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{3{product3[30]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[33:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{3{product4[30]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[33:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{3{product5[30]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[33:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{3{product6[30]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[33:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{3{product7[30]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[33:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{3{product8[30]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[33:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{3{product9[30]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[33:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{3{product10[30]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[33:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{3{product11[30]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[33:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{3{product12[30]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[33:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{3{product13[30]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[33:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{3{product14[30]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[33:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{3{product15[30]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[33:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{3{product16[30]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[33:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{3{product17[30]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[33:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{3{product18[30]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[33:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{3{product19[30]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[33:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{3{product20[30]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[33:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{3{product21[30]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[33:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{3{product22[30]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[33:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{3{product23[30]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[33:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{3{product24[30]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[33:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{3{product25[30]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[33:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{3{product26[30]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[33:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{3{product27[30]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[33:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{3{product28[30]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[33:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{3{product29[30]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[33:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{3{product30[30]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[33:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{3{product31[30]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[33:0];

  assign output_typeconvert = (sum30[31:0] + {sum30[23], {22{~sum30[23]}}})>>>23;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // filter
